name: dart_company_lints
version: 0.1.0
description: >
  Dart lint rules for your company or/and pet projects based on
  (official rules)[https://github.com/dart-lang/lints].
  Defines the 'company' set of lints accepted by the your Dart team.
repository: https://github.com/signmotion/company_lints
topics:
  - analysis
  - lints

environment:
  sdk: ">=3.0.0"

# NOTE: Code is not allowed in this package - do not add dependencies.
# dependencies:

dev_dependencies:
  collection: ^1.17.0
  http: ^1.0.0
  lints: ^2.1.1
  path: ^1.8.0
  yaml: ^3.1.0
